### ISSUE TITLE
Traffic Analyser purging after 3 days of traffic

### ISSUE THREAD

**Issue by notzippy** [paldier/bluecave-merlin#10]
I noticed this with the "factory" ROM as well. After three days the data is purged, is this something that can be modified? I contacted support and of course, they said that is expected due to the free space. So I sym-linked the TrafficAnalyzer database onto the flash drive. That appeared to work fine but it still seems that the data purge is occurring. I'll look through the code, but if you know a way of stopping this then let me know.

Thanks for the port, using Current Version : 3.0.0.4.384_BLUECAVE_R5.0.8-g23e

**Comment by paldier** [comment]
it's closed source,no way

**Comment by Steve-hyas** [comment]
I thought this code  here
https://github.com/paldier/bluecave-merlin/blob/5274f05cc50a0cd99b4d84703034a375b5a1e1fc/release/src/router/rc/hour_monitor.c#L23-L29

May have something to do with the size, given the -d flag

```
# TrafficAnalyzer 
Usage :
  bwdpi_sqlite -s [select] -g [get_table] -e [exec] -p [path] -a [group] -b [having] -t [test mode] -r [rename]
  ex:
  save data            : bwdpi_sqlite -e
  get  data            : bwdpi_sqlite -s [select] -g [get_table] -p [path] -a [group] -b [having]
  test mode when query : bwdpi_sqlite -t [query string]
  rename database      : bwdpi_sqlite -r
  database limit       : bwdpi_sqlite -d [file size: KB]

```

**Comment by paldier** [comment]
do you know that mount usb after jffs is mounted and more than 30 seconds,it's must be 2MB at boot time,you can use /jffs/scripts/post-mount to restart TrafficAnalyzer 
and add  this code
` if(!check_if_file_exist("/mnt/TrafficAnalyzer/path/file"))`
`size = 2 * 1024;	// 2MB`
`else`
`size = 100 * 1024;	// 100MB`

**Comment by Steve-hyas** [comment]
I tried running

```
# TrafficAnalyzer -d 102400
```
will let you know if timeline is extended

**Comment by notzippy** [comment]
Lasted a week, upping 
```
TrafficAnalyzer -d 10240000
```

**Comment by chongaik3** [comment]
You found the way to have longer (more than 1week) traffic info? Can teach me? But i am not techki guy

**Comment by notzippy** [comment]
@chongaik3 Never got it working, sorry
